### ISSUE TITLE
devel jobs depending on locally built debs fail

### ISSUE THREAD

**Issue by jjekircp** [ros-infrastructure/ros_buildfarm#107]
I have a test buildfarm with a set of private packages and I'm noticing that all of the devel jobs that depend on binary packages built locally on the buildfarm are failing.

Specifically, when calling into apt to install the build dependencies after resolving them with rosdep, the build errors out as it can't find the locally built package in apt.
I hand-verified that the package in question made it into the `testing` repo after the build succeeded. It seems on the surface like the build is missing an `apt-get update` call  between when the apt repositories listed in the source build file are added and when the apt package install of the resolved rosdep key is attempted.

A gist of the full build output (with private package names removed) is available below:
https://gist.github.com/jjekircp/0a468c3053e468812af3

**Comment by dirk-thomas** [comment]
If the Debian package is in the testing repo (which is a good sign) it might be some other configuration problem. It might be necessary to post more information about your configuration in order to narrow it down. Can you please point to your `ros_buildfarm_config` fork.

**Comment by jjekircp** [comment]
My `ros_buildfarm_config` fork isn't public, so I've copied the `index.yaml` and `indigo/source-build.yaml` files into a gist:
https://gist.github.com/jjekircp/f06751c49c46d1d95716

Full disclosure: I was a bit short of both disk space and patience when setting up this test buildfarm so I skipped the import-upstream step and instead added `packages.ros.org` to all my build files. This seems to have worked, but I note it here in case it breaks things in ways I haven't seen yet.

**Comment by dirk-thomas** [comment]
Can you please also check / post your rosdistro configuration that you are pointing to the correct cache url (similar to https://github.com/ros/rosdistro/blob/bb026d397e564faaedf5758a3f72e5ced4d931bb/index.yaml#L20 but on your server).

**Comment by jjekircp** [comment]
My rosdistro index.yaml:

```
%YAML 1.1
# ROS index file
# see REP 141: http://ros.org/reps/rep-0141.html
---
distributions:
  indigo:
    distribution: indigo/distribution.yaml
    distribution_cache: http://<repo server>/rosdistro_cache/indigo-cache.yaml.gz
    doc_builds: [indigo/doc-build.yaml]
    release_builds: [indigo/release-build.yaml]
    source_builds: [indigo/source-build.yaml]

type: index
version: 2

```

My rosdistro source-build.yaml:
```
%YAML 1.1
# ROS source-build file
# see REP 141: http://ros.org/reps/rep-0141.html
---
jenkins_job_timeout: 120
jenkins_url: http://jenkins.ros.org
notifications:
  committers: true
  emails:
  - ros-buildfarm-devel@googlegroups.com
  maintainers: true
targets:
  # _config:
  #   apt_mirrors:
  #   - http://repos.ros.org/repos/building/
  ubuntu:
    trusty:
      amd64:
type: source-build
version: 1
```

Does the `apt_mirrors` section here do anything? I was under the impression that that was controlled by the `repositories` key in the source build file in the ros_buildfarm_config repo.
