### ISSUE TITLE
generate_prerelease_script.py bug

### ISSUE THREAD

**Issue by eybee** [ros-infrastructure/ros_buildfarm#97]
Running the following commands
```
mkdir -p /tmp/prerelease_job
cd /tmp/prerelease_job
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml \
  jade default ubuntu trusty amd64 \
  heatmap \
  --level 1 \
  --output-dir ./
```
results in this error
```
Fetching buildfarm configuration...
Fetching rosdistro cache...
Traceback (most recent call last):
  File "/usr/bin/generate_prerelease_script.py", line 263, in <module>
    sys.exit(main())
  File "/usr/bin/generate_prerelease_script.py", line 149, in main
    source_repository.name = 'prerelease'
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by tfoote** [comment]
I can reproduce. 

heatmap is a standalone package without a packages list. This is probably parsing incorrectly. 

```
  heatmap:
    doc:
      type: git
      url: https://github.com/eybee/heatmap.git
      version: jade-devel
    release:
      tags:
        release: release/jade/{package}/{version}
      url: https://github.com/eybee/heatmap-release.git
      version: 0.2.2-0
```

**Comment by meyerj** [comment]
Same for hector_slam:

Running the commands
```
mkdir -p /tmp/prerelease_job
cd /tmp/prerelease_job
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml \
  jade default ubuntu trusty amd64 \
  hector_slam \
  --level 1 \
  --output-dir ./
```

results in

```
Fetching buildfarm configuration...
Fetching rosdistro cache...
Traceback (most recent call last):
  File "/usr/bin/generate_prerelease_script.py", line 281, in <module>
    sys.exit(main())
  File "/usr/bin/generate_prerelease_script.py", line 166, in main
    source_repository.name = 'prerelease'
AttributeError: 'NoneType' object has no attribute 'name'
```

From jade/distribution.yaml:
```
  hector_slam:
    doc:
      type: git
      url: https://github.com/tu-darmstadt-ros-pkg/hector_slam.git
      version: catkin
    release:
      packages:
      - hector_compressed_map_transport
      - hector_geotiff
      - hector_geotiff_plugins
      - hector_imu_attitude_to_tf
      - hector_imu_tools
      - hector_map_server
      - hector_map_tools
      - hector_mapping
      - hector_marker_drawing
      - hector_nav_msgs
      - hector_slam
      - hector_slam_launch
      - hector_trajectory_server
      tags:
        release: release/jade/{package}/{version}
      url: https://github.com/tu-darmstadt-ros-pkg-gbp/hector_slam-release.git
    status: maintained
```

I think the issue is that hector_slam does not have the `source:` tag (We do not want the ROS buildfarm to send mails to the developers). If I run the script with

```
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml \
  jade default ubuntu trusty amd64 \
  --custom-repo hector_slam:git:https://github.com/tu-darmstadt-ros-pkg/hector_slam.git:catkin \
  --level 1 \
  --output-dir ./
```

it seems to work fine (prerelase is still running...).

With the source section added to distribution.yaml for heatmap in ros/rosdistro#9290 this issue is probably solved, except that there should be a more expressive error message in that case.
